# This workflow builds branches and runs tests when PRs are raised. No docker image is built here
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Branch PR workflow

on:
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    name: Running tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run tests
        run: mvn clean test jacoco:report
      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
